version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend
    expose:
      - "5000"
    networks:
      - appnet

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - appnet

  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - "8080:80"
    volumes:
      - ./tools/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
